### ISSUE TITLE
Deprecated selector in `zir-atom-dark-ui\index.less`

### ISSUE THREAD

**Issue by ghost** [Zireael/zir-atom-dark-ui#1]
In `zir-atom-dark-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow,
atom-text-editor .gutter .line-number,
atom-text-editor .line` => `atom-text-editor.editor,
atom-text-editor .gutter .line-number,
atom-text-editor .line`

* `atom-text-editor::shadow .line-numbers` => `atom-text-editor.editor .line-numbers`

* `atom-text-editor::shadow .line-numbers .line-number` => `atom-text-editor.editor .line-numbers .line-number`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   1)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   1)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   1).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   1).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   2)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   2)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   2).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   2).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   3)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   3)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   3).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   3).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   4)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   4)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   4).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   4).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   5)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   5)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   5).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   5).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   6)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   6)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   6).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   6).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   7)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   7)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   7).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   7).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   8)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   8)`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   8).indent-guide-active` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   8).indent-guide-active`

* `atom-text-editor::shadow .indent-guide-stack:nth-child(20n   9)` => `atom-text-editor.editor .indent-guide-stack:nth-child(20n   9)`

* `atom-text-editor::shadow .

**Comment by Zireael** [comment]
Removed 1 shadow selector in editor.less at `atom-text-editor .line-numbers`
